<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="11607" started-at="2020-07-27T03:37:49Z" finished-at="2020-07-27T03:38:01Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="11607" started-at="2020-07-27T03:37:49Z" finished-at="2020-07-27T03:38:01Z">
      <class name="Services.AssertionTest">
        <test-method status="PASS" signature="getData()[pri:0, instance:Services.AssertionTest@38203]" name="getData" is-config="true" duration-ms="634" started-at="2020-07-27T09:07:49Z" finished-at="2020-07-27T09:07:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getData -->
        <test-method status="PASS" signature="getApiAssertion1Test()[pri:0, instance:Services.AssertionTest@38203]" name="getApiAssertion1Test" duration-ms="9620" started-at="2020-07-27T09:07:50Z" finished-at="2020-07-27T09:07:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getApiAssertion1Test -->
        <test-method status="PASS" signature="getApiAssertion2Test()[pri:0, instance:Services.AssertionTest@38203]" name="getApiAssertion2Test" duration-ms="168" started-at="2020-07-27T09:07:59Z" finished-at="2020-07-27T09:07:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getApiAssertion2Test -->
        <test-method status="PASS" signature="getApiAssertion3Test()[pri:0, instance:Services.AssertionTest@38203]" name="getApiAssertion3Test" duration-ms="973" started-at="2020-07-27T09:07:59Z" finished-at="2020-07-27T09:08:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getApiAssertion3Test -->
        <test-method status="FAIL" signature="getApiAssertion4Test()[pri:0, instance:Services.AssertionTest@38203]" name="getApiAssertion4Test" duration-ms="181" started-at="2020-07-27T09:08:00Z" finished-at="2020-07-27T09:08:01Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Assertion4 Result:Fail as company name is not same as 'ABC Infotech' expected [ABC Infotech] but found [IG Infotech]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Assertion4 Result:Fail as company name is not same as 'ABC Infotech' expected [ABC Infotech] but found [IG Infotech]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at Services.AssertionTest.getApiAssertion4Test(AssertionTest.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getApiAssertion4Test -->
      </class> <!-- Services.AssertionTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
